/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.ahana.presto.datagen;

import java.util.List;

public class TestDataGenCatalogParser
{
    public static final String TEST_SCHEMALIST_JSON = String.join("\n",
            "[",
            "    {",
            "        \"name\": \"first\",",
            "        \"tables\": [",
            "            {",
            "                \"name\": \"tb\",",
            "                \"columns\": [",
            "                    {",
            "                        \"name\": \"u\",",
            "                        \"type\": \"BIGINT\"",
            "                    }",
            "                ],",
            "                \"splitSpecs\": [",
            "                    {",
            "                        \"rowCount\": 10,",
            "                        \"columnStats\": [",
            "                            {",
            "                                \"name\": \"u\",",
            "                                \"stats\": {",
            "                                    \"type\": \"base\",",
            "                                    \"min\": 1,",
            "                                    \"max\": 3,",
            "                                    \"distinctValsCount\": 2",
            "                                 }",
            "                            }",
            "                        ]",
            "                    },",
            "                    {",
            "                        \"rowCount\": 5,",
            "                        \"columnStats\": [",
            "                            {",
            "                                \"name\": \"u\",",
            "                                \"stats\": {",
            "                                    \"type\": \"base\",",
            "                                    \"min\": 4,",
            "                                    \"max\": 9,",
            "                                    \"distinctValsCount\": 3",
            "                                 }",
            "                            }",
            "                        ]",
            "                    }",
            "                ]",
            "            }",
            "        ]",
            "    },",
            "    {",
            "        \"name\": \"second\",",
            "        \"tables\": [",
            "            {",
            "                \"name\": \"t\",",
            "                \"columns\": [",
            "                    {",
            "                        \"name\": \"u\",",
            "                        \"type\": \"INTEGER\"",
            "                    },",
            "                    {",
            "                        \"name\": \"v\",",
            "                        \"type\": \"DOUBLE\"",
            "                    },",
            "                    {",
            "                        \"name\": \"w\",",
            "                        \"type\": \"VARCHAR\"",
            "                    }",
            "                ],",
            "                \"splitSpecs\": [",
            "                    {",
            "                        \"rowCount\": 10,",
            "                        \"columnStats\": [",
            "                            {",
            "                                \"name\": \"u\",",
            "                                \"stats\": {",
            "                                    \"type\": \"base\",",
            "                                    \"min\": 1,",
            "                                    \"max\": 3,",
            "                                    \"distinctValsCount\": 2",
            "                                 }",
            "                            },",
            "                            {",
            "                                \"name\": \"v\",",
            "                                \"stats\": {",
            "                                    \"type\": \"base\",",
            "                                    \"min\": 5.5,",
            "                                    \"max\": 7.0,",
            "                                    \"distinctValsCount\": 3",
            "                                 }",
            "                            },",
            "                            {",
            "                                \"name\": \"w\",",
            "                                \"stats\": {",
            "                                    \"type\": \"base\",",
            "                                    \"min\": \"BAX\",",
            "                                    \"max\": \"CZX\",",
            "                                    \"distinctValsCount\": 3",
            "                                 }",
            "                            }",
            "                        ]",
            "                    }",
            "                ]",
            "            }",
            "        ]",
            "    }",
            "]");
}
